### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by jadedevin13** [getsandbox/sandbox#13]
Debian 8
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)

{"errors":[{"message":"Application is missing main.js (or its empty) - please add this file and commit"}]}

**Comment by nhoughto** [comment]
Hey

Need more info to figure out what your problem is, what are your arguments, what does your main.js / routes look like? etc

**Comment by psypilat** [comment]
Experiencing the same issue. Tried both docker container and binary on ubuntu.
`Engine: 1684230058 - Exception handling routing table request
com.sandbox.runtime.models.ServiceScriptException: Application is missing main.js (or its empty) - please add this file and commit
        at com.sandbox.runtime.js.services.Service.loadService(Service.java:192)
        at com.sandbox.runtime.js.services.Service.initialize(Service.java:101)
        at com.sandbox.runtime.js.services.Service.handleRoutingTableRequest(Service.java:150)
        at com.sandbox.runtime.HttpRequestHandler.getOrCreateRoutingTable(HttpRequestHandler.java:261)
        at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:166)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Error processing request
com.sandbox.runtime.models.ServiceScriptException: Application is missing main.js (or its empty) - please add this file and commit
        at com.sandbox.runtime.js.services.Service.loadService(Service.java:192)
        at com.sandbox.runtime.js.services.Service.initialize(Service.java:101)
        at com.sandbox.runtime.js.services.Service.handleRoutingTableRequest(Service.java:150)
        at com.sandbox.runtime.HttpRequestHandler.getOrCreateRoutingTable(HttpRequestHandler.java:261)
        at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:166)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)`
