### ISSUE TITLE
Invalid route exception

### ISSUE THREAD

**Issue by venantius** [getsandbox/sandbox#3]
Hiyo!

I just downloaded the client and started fiddling with it. It seems to work fine, but generates some rather verbose error messages even while returning valid 200 responses. Any thoughts on what the deal is here?

Here's the relevant section of main.js:
```javascript
Sandbox.define('/','GET', function(req, res) {
    // Set the type of response, sets the Content-Type header.
    res.type('application/json');
    
    // Set the status code of the response.
    res.status(200);
    
    // Send the response body.
    res.json({
        "status": "ok"
    });
})
```

Exception:
```
>> HTTP GET /  (Matched route '/')
>> Headers: {Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, Accept-Encoding=gzip, deflate, sdch, Accept-Language=en-US,en;q=0.8, Cache-Control=max-age=0, Connection=keep-alive, Host=localhost:8080, User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36}
>> No body found
<< Status: 200 (took 635ms)
<< Headers: {Content-Type=application/json}
<< Body: '{   "status" : "ok" }'
Error processing request
java.lang.Exception: Invalid route
	at com.sandbox.runtime.HttpRequestHandler.findMatchedRoute(HttpRequestHandler.java:199) ~[sandbox:na]
	at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:96) ~[sandbox:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [sandbox:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:370) [sandbox:na]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [sandbox:na]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [sandbox:na]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [sandbox:na]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [sandbox:na]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [sandbox:na]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [sandbox:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [sandbox:na]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [sandbox:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [sandbox:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [sandbox:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by nhoughto** [comment]
Hey
My bet is that you are testing this GET route with your browser? When you issue a request from your browser is often makes a second request to retrieve the '/favicon.ico' file for the given URL. This is obviously an invalid route because you have only defined a '/' route. If you used a proper client to make the request (like your application) or a client like Postman for chrome you wouldn't see this problem.

Thanks for the feedback.

**Comment by venantius** [comment]
Ah, you're probably right -- I am using a browser rather than a pure client, and curl seems to work fine. Would be nice to have some more helpful error handling around that (e.g. something to the effect of the path being requested that's invalid)

**Comment by nhoughto** [comment]
yeah its not super obvious is it, will add to the backlog.

**Comment by nhoughto** [comment]
Errors are now logged with an invalid path message rather than an Exception.
