### ISSUE TITLE
How do i run main.js from example

### ISSUE THREAD

**Issue by palaniraja** [getsandbox/sandbox#41]
None of the following command worked

```
./sandbox run --port=8080
./sandbox run --port=8080 main.js
./sandbox run examples/main.js
./sandbox run --base=examples/
./sandbox run
./sandbox run --verbose
```

All start the server

```
Sandbox ready (build: v1.0.238-91a287a runtime: VERSION_2) --  Running on port: 8080, metadata on port: disabled, reading from path: '/Users/palaniraja/Desktop/getsandbox' with 1 -> 4 worker(s)
```

But when I try to request  `http://localhost:8080/test` I only get

```
{"errors":[{}]}
```

This is my folder structure. I have `main.js` in both current directory as well as `examples/main.js`

```

➜  getsandbox find .
.
./main.js
./sandbox
./examples
./examples/main.js
```

**Comment by stringy05** [comment]
Put run after the arguments
If you run sandbox from the same dir as main.js, then this will work

./sandbox --port=10080 --verbose run

**Comment by palaniraja** [comment]
No Luck!

May be because of java warnings below?

```
➜  getsandbox ./sandbox --verbose run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/palaniraja/Desktop/getsandbox/sandbox) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sandbox ready (build: v1.0.238-91a287a runtime: VERSION_2) --  Running on port: 8080, metadata on port: disabled, reading from path: '/Users/palaniraja/Desktop/getsandbox' with 1 -> 4 worker(s)
Error processing request
java.lang.NullPointerException: null
	at com.sandbox.runtime.js.services.JSEngineService.createNewContext(JSEngineService.java:107)
	at com.sandbox.runtime.js.services.JSEngineService.createEngine(JSEngineService.java:86)
	at com.sandbox.runtime.js.services.JSEngineService.createOrGetEngine(JSEngineService.java:78)
	at com.sandbox.runtime.js.services.ServiceManager.createService(ServiceManager.java:102)
	at com.sandbox.runtime.js.services.ServiceManager.getService(ServiceManager.java:98)
	at com.sandbox.runtime.HttpRequestHandler.getRuntimeService(HttpRequestHandler.java:253)
	at com.sandbox.runtime.HttpRequestHandler.getOrCreateRoutingTable(HttpRequestHandler.java:261)
	at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:166)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:835)
^C%
```

Sorry, I ignored them in my prev. comment, considering i still get JSON response, and it was only warning.

`http://localhost:10080/test` and `http://localhost:10080/users` return same response `{"errors":[{}]}`

**Comment by palaniraja** [comment]
Even after adding `java --add-opens java.base/java.lang=ALL-UNNAMED -jar` I get the same error mentioned above


```
➜  getsandbox java --add-opens java.base/java.lang=ALL-UNNAMED -jar  sandbox --port=10080 --verbose run
Sandbox ready (build: v? runtime: VERSION_2) --  Running on port: 10080, metadata on port: disabled, reading from path: '/Users/palaniraja/Desktop/getsandbox' with 1 -> 4 worker(s)
Error processing request
java.lang.NullPointerException: null
	at com.sandbox.runtime.js.services.JSEngineService.createNewContext(JSEngineService.java:107)
	at com.sandbox.runtime.js.services.JSEngineService.createEngine(JSEngineService.java:86)
	at com.sandbox.runtime.js.services.JSEngineService.createOrGetEngine(JSEngineService.java:78)
	at com.sandbox.runtime.js.services.ServiceManager.createService(ServiceManager.java:102)
	at com.sandbox.runtime.js.services.ServiceManager.getService(ServiceManager.java:98)
	at com.sandbox.runtime.HttpRequestHandler.getRuntimeService(HttpRequestHandler.java:253)
	at com.sandbox.runtime.HttpRequestHandler.getOrCreateRoutingTable(HttpRequestHandler.java:261)
	at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:166)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:835)



```

**Comment by nhoughto** [comment]
You can't use Java 11+ as Oracle have removed Nashorn, which is pretty critical.
Use Java 8-10 (ideally 8 its most well tested), until the new version is released that migrates of Nashorn. You can test it out via docker image now if feeling brave.

https://hub.docker.com/r/getsandbox/worker-cli

**Comment by palaniraja** [comment]
Tested with 10.0.0.2 I get the same error.

```
➜  getsandbox java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

➜  getsandbox java --add-opens java.base/java.lang=ALL-UNNAMED -jar  sandbox --port=10080 --verbose run
Sandbox ready (build: v? runtime: VERSION_2) --  Running on port: 10080, metadata on port: disabled, reading from path: '/Volumes/Data/development/source/try/getsandbox' with 1 -> 4 worker(s)
Error processing request
java.lang.NullPointerException: null
    at com.sandbox.runtime.js.services.JSEngineService.createNewContext(JSEngineService.java:107)
    at com.sandbox.runtime.js.services.JSEngineService.createEngine(JSEngineService.java:86)
    at com.sandbox.runtime.js.services.JSEngineService.createOrGetEngine(JSEngineService.java:78)
    at com.sandbox.runtime.js.services.ServiceManager.createService(ServiceManager.java:102)
    at com.sandbox.runtime.js.services.ServiceManager.getService(ServiceManager.java:98)
    at com.sandbox.runtime.HttpRequestHandler.getRuntimeService(HttpRequestHandler.java:253)
    at com.sandbox.runtime.HttpRequestHandler.getOrCreateRoutingTable(HttpRequestHandler.java:261)
    at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:166)
    at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:502)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
    at java.base/java.lang.Thread.run(Thread.java:844)
^C%                                                                                                 
```

`http://localhost:10080/test` return the below json instead of expected `Hello world`


```
{"errors":[{}]}
```

**Comment by nhoughto** [comment]
You are right, likely some other interaction with the new module changes in Java 9.
I'd still recommend Java 8, until new runtime comes out. I'll re-open this as it should work :+1:

**Comment by nhoughto** [comment]
So as expected this was just a Java 9+ modules thing, if you run it with the correct modules it works as expect on Java 9 and Java 10, not 11+ obv as nashorn is gone

`--add-modules java.base,java.scripting,java.xml,jdk.dynalink,jdk.scripting.nashorn,jdk.xml.bind,jdk.xml.dom,jdk.xml.ws`
